(function(){
const C=window.TRACKFYP_CONFIG||{}; const BASE=window.BASE||'';
const nav=[['index.html','Home','Home'],['tools/analyze.html','Analyze','Analyze'],['tools/hashtag-generator.html','Hashtags','Hashtags'],['tools/best-time.html','Best Time','Best Time'],['blog/index.html','Blog','Blog'],['premium.html','Premium','Premium']];
function header(){let e=document.getElementById('site-header');if(!e)return;e.innerHTML=`<header class="nav"><div class="nav-row"><a class="brand" href="${BASE}index.html">Track<span>Fyp</span></a><nav class="nav-links" id="navLinks">${nav.map(x=>`<a href="${BASE+x[0]}" data-ur="${x[1]}" data-en="${x[2]}">${x[1]}</a>`).join('')}<div class="lang-switch"><button class="lang-btn" data-lang="ur">Roman Urdu</button><button class="lang-btn" data-lang="en">English</button></div></nav><button class="menu-toggle" id="menuToggle">☰</button></div></header>`;document.getElementById('menuToggle').onclick=()=>document.getElementById('navLinks').classList.toggle('open')}
function footer(){let e=document.getElementById('site-footer');if(!e)return;e.innerHTML=`<footer><div class="container foot"><div>© TrackFyp — AI TikTok Growth Assistant</div><div><a href="${BASE}about.html">About</a> · <a href="${BASE}privacy.html">Privacy</a> · <a href="${BASE}terms.html">Terms</a></div></div></footer>`}
function lang(l){document.querySelectorAll('[data-ur]').forEach(e=>{let v=e.getAttribute(l==='ur'?'data-ur':'data-en');if(v!==null)e.innerHTML=v});document.querySelectorAll('[data-ur-ph]').forEach(e=>e.placeholder=l==='ur'?e.dataset.urPh:e.dataset.enPh);document.querySelectorAll('.lang-btn').forEach(b=>b.classList.toggle('active',b.dataset.lang===l));localStorage.setItem('trackfyp_lang',l)}
function initLang(){let l=localStorage.getItem('trackfyp_lang')||'ur';document.querySelectorAll('.lang-btn').forEach(b=>b.onclick=()=>lang(b.dataset.lang));lang(l)}
window.api=async function(path,opts={}){let r=await fetch((C.API_BASE||'')+path,opts);let data;try{data=await r.json()}catch{data={error:await r.text()}}if(!r.ok)throw new Error(data.error||'Request failed');return data};
window.showResult=(id,html)=>{let e=document.getElementById(id);if(e){e.innerHTML=html;e.classList.add('show')}};
window.escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
document.addEventListener('DOMContentLoaded',()=>{header();footer();initLang();let p=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.nav-links a').forEach(a=>{if(a.getAttribute('href').endsWith(p))a.classList.add('active')})});
})();
